### ISSUE TITLE
ReadOnlyRootFilesystem recommendation should be listed in the Pod Security category

### ISSUE THREAD

**Issue by sotoiwa** [aws/aws-eks-best-practices#103]
**Describe the problem**
In the [Image Security](https://aws.github.io/aws-eks-best-practices/security/docs/image/) category, there is a recommendation of "[Configure your images with read-only root file system](https://aws.github.io/aws-eks-best-practices/security/docs/image/#configure-your-images-with-read-only-root-file-system)". I agree with the content, but since this is not an image configuration, wouldn't it be more appropriate to put it in the [Pod Security](https://aws.github.io/aws-eks-best-practices/security/docs/pods/) category?

**References**
https://aws.github.io/aws-eks-best-practices/security/docs/image/#configure-your-images-with-read-only-root-file-system

**Comment by jicowan** [comment]
Makes sense. Thanks for the suggestion.

**Comment by jicowan** [comment]
https://github.com/aws/aws-eks-best-practices/commit/108592f85a2bb0abf50cbc7805a900b4f4c2f96c#diff-468dbcbb748b6c19b5a65fb5d2f97d4469ba975b3ea6512bf30b8fe145f6cf03
