### ISSUE TITLE
Duplicate recommendations about running containers as non-root user

### ISSUE THREAD

**Issue by sotoiwa** [aws/aws-eks-best-practices#109]
**Describe the problem**
There are duplicate recommendations about running the container as a non-root user in both the [IAM category](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#run-the-application-as-a-non-root-user) and the [Pod Security category](https://aws.github.io/aws-eks-best-practices/security/docs/pods/#do-not-run-processes-in-containers-as-root) .

The descriptions in the IAM and Pod Security categories are duplicated, and since they are about the securityContext, I think it is better to put it only in the Pod Security category.

It's also mentioned in the [Image category](https://aws.github.io/aws-eks-best-practices/security/docs/image/#add-the-user-directive-to-your-dockerfiles-to-run-as-a-non-root-user), but I think that's fine as it's about specifying the USER in the Dockerfile.

**References**
https://aws.github.io/aws-eks-best-practices/security/docs/iam/#run-the-application-as-a-non-root-user
https://aws.github.io/aws-eks-best-practices/security/docs/pods/#do-not-run-processes-in-containers-as-root
https://aws.github.io/aws-eks-best-practices/security/docs/image/#add-the-user-directive-to-your-dockerfiles-to-run-as-a-non-root-user

**Comment by jicowan** [comment]
You can never say it enough, right? I'll consider removing it from the IAM category. Thanks for pointing it out.
