### ISSUE TITLE
Cluster Autoscaling Guide 404 and Asset Errors

### ISSUE THREAD

**Issue by akestner** [aws/aws-eks-best-practices#113]
**Describe the problem**
Visiting the Cluster Autoscaling guide page (https://aws.github.io/aws-eks-best-practices/cluster-autoscaling/cluster-autoscaling/) results in broken Javascript, CSS and a 404 error. I'm not sure if this is simply an issue with the link in the navigation or with the page itself.

**Screenshot**
![image](https://user-images.githubusercontent.com/3409228/124670322-aae48480-de68-11eb-9a87-84fb7fce1106.png)

**Comment by jicowan** [comment]
Looking into it. Thanks for filing an issue.

**Comment by jicowan** [comment]
Fixed in https://github.com/aws/aws-eks-best-practices/commit/e13403ea0026ee6678a6165937763efc56ce6d3f
