### ISSUE TITLE
 Broken link to the k8s audit policy that EKS uses as a base

### ISSUE THREAD

**Issue by sotoiwa** [aws/aws-eks-best-practices#115]
**Describe the problem**
At the top of the Detective Control section, it mentions the k8s audit policy that EKS uses. The range of lines in the linked code is not correct because the referenced configure-helper.sh has been updated.

The guide refers to [L983-L1108,](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L983-L1108) but [L1116-L1241](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L1116-L1241) seems to be correct at this moment.

Is EKS still using this latest updated GCP configure-helper.sh as a base? The EKS user guide does not mention the k8s audit policy that EKS uses. 

**References**
https://aws.github.io/aws-eks-best-practices/security/docs/detective.html

**Comment by jicowan** [comment]
EKS is using a slightly modified version of the policy in the script file. I will try to update with the actual audit policy. It wasn't available at the time I wrote this.

**Comment by jicowan** [comment]
Updated documentation.

**Comment by sotoiwa** [comment]
Thanks for the update! I think this might be better stated in the user guide rather than the best practices guide.
