### ISSUE TITLE
CNI custom networking for managed node groups

### ISSUE THREAD

**Issue by mehrajk** [aws/aws-eks-best-practices#119]
**Describe the problem**
The web page section "EKS managed node groups currently don’t support custom networking option." This conflicts with AWS official documentation.
https://aws.github.io/aws-eks-best-practices/reliability/docs/networkmanagement/#cni-custom-networking indicates "

**References**
Web page section: https://aws.github.io/aws-eks-best-practices/reliability/docs/networkmanagement/#cni-custom-networking : Claims "EKS managed node groups currently don’t support custom networking option."

AWS official docs: https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html  shows example with managed node groups.

**Comment by jicowan** [comment]
Thanks @mehrajk. I will update the guide to reflect the changes to the service. At the time this was written, custom networking was not supported.

**Comment by jicowan** [comment]
@realvz Can you have a look at this?
