### ISSUE TITLE
IAM roles for service accounts 

### ISSUE THREAD

**Issue by mannbiher** [aws/aws-eks-best-practices#128]
**Describe the problem**
I am trying to understand how IAM roles for service accounts work and below lines in "IAM Roles for Service Accounts" section in iam page looks confusing or incorrect.

`Pods with service accounts that reference an IAM Role call a public OIDC discovery endpoint for AWS IAM upon startup. The endpoint cryptographically signs the OIDC token issued by Kubernetes which ultimately allows the Pod to call the AWS APIs associated IAM role.`

What I found it is Kubelet which makes call to Kubernetes API server TokenRequest endpoint (not OIDC discovery endpoint) and then mounts the signed OIDC token received as projected volume on the pod. Pod service account doesn't have RBAC permissions to request token and thus cannot do it itself.

New EKS user here, so I might be wrong, in that case could we get some more information or example as how pod requests endpoint to sign OIDC token.

**References**
Please include a link to the lines where the error appears.
https://github.com/aws/aws-eks-best-practices/blob/master/content/security/docs/iam.md#iam-roles-for-service-accounts-irsa

**Comment by jicowan** [comment]
The Kubernetes-issued OIDC token, i.e. the projected service account token, is exchanged for AWS role credentials when the AWS SDK calls AssumeRoleWithWebIdentity. On EKS we give pod a that is assigned an IAM role a cryptographically-signed token which can be verified by STS against the OIDC discovery endpoint. See https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/ for further details. If you feel that there is a better way to say this, can you suggest alternate verbiage?

**Comment by mannbiher** [comment]
I think aws-eks-best-practices documentation is pretty clear on passing OIDC token to STS. It is the `pod calling OIDC discovery endpoint` lines that I am concerned about. I looked at the EKS node and pod logs and this doesn't seem to happen. Kubelet makes call to Kube API server to get cryptographically-signed token and then mount it to pod. Pod has the token before start without contacting OIDC endpoint.
`Pods with service accounts that reference an IAM Role call a public OIDC discovery endpoint for AWS IAM upon startup`
Your comment has more accurate description of what actually happens.
`On EKS we give pod a that is assigned an IAM role a cryptographically-signed token which can be verified by STS against the OIDC discovery endpoint`
Replace we with Kubelet and Kubernetes API server and it becomes less confusing.

**Comment by mannbiher** [comment]
A simpler explanation could be (hiding the minute details). I could open a PR if this looks Ok.
`Pod with service account that reference an IAM role are provided with cryptographically-signed token issued by OIDC provider. These tokens can be verified using public OIDC provider which ultimately allows the Pod to call the AWS APIs associated IAM role.`

**Comment by jicowan** [comment]
Yes, the pod doesn't call the discovery endpoint directly. I can clarify that part. This image does a better job of explaining it. The OIDC endpoint signs the token issued by k8s. 

![image](https://user-images.githubusercontent.com/8750251/140570621-355a9e02-e6be-4a65-b5e6-cf5c88664bc5.png)

**Comment by mannbiher** [comment]
Thank you that would help.

**Comment by jicowan** [comment]
addressed by https://github.com/aws/aws-eks-best-practices/commit/d2dce2d990e7b794dfbe5f4b226572337899a090
