### ISSUE TITLE
Conflict regarding node group balancing for cluster-autoscaling/co-scheduling 

### ISSUE THREAD

**Issue by chgerkens** [aws/aws-eks-best-practices#140]
**Describe the problem**

> Node group balancing is **enabled** by setting balance-similar-node-groups=**false**

**References**
[cluster-autoscaling/#co-scheduling](https://aws.github.io/aws-eks-best-practices/cluster-autoscaling/#co-scheduling)

**Comment by jicowan** [comment]
Thanks @chgerkens. I will try to get to this over the next couple weeks when things start to slow down.

**Comment by jicowan** [comment]
fixed.
