### ISSUE TITLE
Typo: encrypted in Secrets management section of Data encryption and secrets management

### ISSUE THREAD

**Issue by harikiranvusirikala** [aws/aws-eks-best-practices#141]
**Describe the problem**
Letter "r" is missing in encrypted.
=> On EKS, the EBS volumes for etcd nodes are **encypted** with EBS encryption. -> On EKS, the EBS volumes for etcd nodes are **encrypted** with EBS encryption.

**Link to resource**
[Data encryption and secrets management -> Secrets management](https://github.com/aws/aws-eks-best-practices/blob/master/content/security/docs/data.md#secrets-management)

**References**
From GitHub
<img width="1063" alt="Screenshot 2021-12-17 at 8 01 36 PM" src="https://user-images.githubusercontent.com/25457325/146559778-27a25333-b85c-4466-b5f5-366d86cc5f15.png">
From aws.github.io
<img width="728" alt="Screenshot 2021-12-17 at 8 04 02 PM" src="https://user-images.githubusercontent.com/25457325/146560145-2affed47-f99a-48b6-871f-27236769da3b.png">

**Comment by jicowan** [comment]
fixed.
