### ISSUE TITLE
Write blurb on using OPA as an alternative to PSPs

### ISSUE THREAD

**Issue by jicowan** [aws/aws-eks-best-practices#16]
**Is your idea request related to a problem that you've solved? Please describe.**
A clear and concise description of the problem.

**Describe the best practice**
A clear and concise description of the best practice you developed along with any code and/or projects you used to solve the problem.

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the idea here.
based on content from https://www.infracloud.io/kubernetes-pod-security-policies-opa/

**Comment by mhausenblas** [comment]
We should also include [Gatekeeper's support for PSP](https://github.com/open-policy-agent/gatekeeper/tree/master/library/pod-security-policy) here.

**Comment by joebowbeer** [comment]
@jicowan Currently, OPA Gatekeeper is only mentioned in two links in a [Tools and Resources](https://aws.github.io/aws-eks-best-practices/security/docs/pods/#tools-and-resources) section below the article. Is this adequate guidance? (I ask this naively not rhetorically.)

Given that PSP is deprecated, I'm trying to determine what the best practice should be regarding pod security. Can you discuss the decision of whether to replace and/or augment PSP with Gatekeeper or Kyverno in the body of this section? I would appreciate it if you could recommend a course of action. Or are we to assume that we should stick with PSP for now, even if we are creating a new cluster?

**Comment by jicowan** [comment]
Thanks for the feedback @joebowbeer. You have roughly 2 years to decide. Until then, you can continue using PSPs or, once it emerges from alpha, you can use the PSP Replacement (presently, EKS only supports beta and GA features). If you have complex policy requirements you may want to consider using OPA, e.g. if you need to validate elements of the pod specification outside of securityContext. Here is a brief but good discussion on the deprecation of PSP, https://youtu.be/2G09tl9Gx_Q?t=638.
