### ISSUE TITLE
Kubectl patch/apply to remove unauthenticated role instead of kubectl edit

### ISSUE THREAD

**Issue by nirroz93** [aws/aws-eks-best-practices#166]
**Describe the problem**
[Here](https://github.com/aws/aws-eks-best-practices/blob/master/content/security/docs/iam.md#review-and-revoke-unnecessary-anonymous-access)  the instructions are kubectl edit, it's easier to do it with kubectl patch or apply, less human mistakes :-)

Using jq, the command can be
`kubectl get ClusterRoleBinding  -o json  | jq -r '.items[] |  select(.subjects[]?.name =="system:unauthenticated") | select(.metadata.name != "system:public-info-viewer") | del(.subjects[] | select(.name =="system:unauthenticated"))' | kubectl apply -f -`

And the last pipe can show the changes (or just pipe to .metadata.name)...

Not sure if it's by intention or not,  but a command helps (instead of anyone building it by themself).
**References**
https://github.com/aws/aws-eks-best-practices/blob/master/content/security/docs/iam.md#review-and-revoke-unnecessary-anonymous-access

**Comment by jicowan** [comment]
Thanks @nirroz93! Would you mind submitting a PR for this?
