### ISSUE TITLE
EKS support for FlexVolume Plugin

### ISSUE THREAD

**Issue by metabc** [aws/aws-eks-best-practices#17]
**Is there a way to support FlexVolume plugin in EKS?**

Currently, the only supported CSi drivers on EKS are EBS, EFS and FSx for Lustre storage classes but these storage classes can’t be used on windows pods that require access to file shares (File shares in windows natively use SMB protocol).
 
Kubernetes has an alternative way to support SMB storage classes – Flexvolume plugin. The issue is this plugin is required to be installed on both master and worker nodes but since EKS doesn’t give access to the control plane "Master node", it makes it difficult to install the plugin. 

The installation guide for flexvolume can be found here - [](https://labs.consol.de/kubernetes/2018/05/11/cifs-flexvolume-kubernetes.html) and [](https://github.com/fstab/cifs)

It requires this command run on  each  node

`VOLUME_PLUGIN_DIR="/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
mkdir -p "$VOLUME_PLUGIN_DIR/fstab~cifs"
cd "$VOLUME_PLUGIN_DIR/fstab~cifs"
curl -L -O https://raw.githubusercontent.com/fstab/cifs/master/cifs
chmod 755 cifs`

This installation guide works well on self-managed K8s cluster.

**Comment by jicowan** [comment]
@metabc Thanks for opening an issue.  This is a great suggestion, however, this is a best practice guide about security.  Could you open an issue on the [containers roadmap](https://github.com/aws/containers-roadmap/projects/1) instead? Thanks!
