### ISSUE TITLE
least-previlege IAM permission for Cluster Autoscaler

### ISSUE THREAD

**Issue by black-mirror-1** [aws/aws-eks-best-practices#182]
**Is your idea request related to a problem that you've solved? Please describe.**
A clear and concise description of the problem.

The [IAM permissions](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html#ca-create-policy) used for the Cluster Autoscaler gives access `SetDesiredCapacity` and `TerminateInstanceInAutoScalingGroup` for all the Autoscaling groups. Even though the Cluster autoscaler deployment container command `--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/<YOUR CLUSTER NAME>` limits it to auto discover ASGs with the specific tags, if someone misses to apply the tags and not add this `k8s.io/cluster-autoscaler/<YOUR CLUSTER NAME>` your cluster autoscaler can potentially scale down instances from an ASG that is not related to the cluster.

**Describe the best practice**
A clear and concise description of the best practice you developed along with any code and/or projects you used to solve the problem.

Apply least-privilege principle and limit the IAM permissions to the ASGs using the same tag.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:ResourceTag/k8s.io/cluster-autoscaler/<my-cluster>": "owned"
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeAutoScalingGroups",
                "ec2:DescribeLaunchTemplateVersions",
                "autoscaling:DescribeTags",
                "autoscaling:DescribeLaunchConfigurations"
            ],
            "Resource": "*"
        }
    ]
}
```
**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the idea here.

**Comment by nublarsec** [comment]
I agree about using an IAM policy that is tightly scoped to just the appropriate ASGs.

We've been using both of the standard tags in the condition:

```json
"Condition": {
    "StringEquals": {
        "autoscaling:ResourceTag/k8s.io/cluster-autoscaler/enabled": "true",
        "autoscaling:ResourceTag/k8s.io/cluster-autoscaler/<our-cluster-name>": "owned"
    }
},
```

@black-mirror-1 Are you working on this? If not I could write this up.

**Comment by black-mirror-1** [comment]
thanks @nublarsec. Yes i will be working on this.
