### ISSUE TITLE
Suggest a minimal IAM policy replacing SSH in "Minimize access to worker nodes"

### ISSUE THREAD

**Issue by tomekchime** [aws/aws-eks-best-practices#187]
**Is your idea request related to a problem that you've solved? Please describe.**
The ["Minimize access to worker nodes"](https://aws.github.io/aws-eks-best-practices/security/docs/hosts/#minimize-access-to-worker-nodes) section of "Protecting the infrastructure (hosts)" mentions the following:

> Instead of enabling SSH access, use [SSM Session Manager](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html) when you need to remote into a host.

If you follow [the guide](https://github.com/aws-samples/ssm-agent-daemonset-installer#installation-instructions) linked to in the section, it recommends adding the `AmazonSSMManagedInstanceCore` AWS managed policy. This policy gives `*` permissions for `ssm:GetParameter(s)` which I believe would allow for that role to access all parameters in Parameter Store (including SecureStrings with the AWS managed KMS key configured).

**Describe the best practice**
I believe the minimal IAM policy mentioned in [this comment](https://github.com/hashicorp/packer/issues/8242#issuecomment-596819349) would be a better alternative if you just want to replace SSH access for your nodes.

**Describe alternatives you've considered**
Copying the `AmazonSSMManagedInstanceCore` policy and removing `ssm:GetParameter(s)`

**Additional context**
* https://repost.aws/questions/QU42Uu_rEcRjagTuMTxVsLZQ/what-resources-do-ssm-managed-instances-actually-need-permissions-for

**Comment by tomekchime** [comment]
🤔 Might want to recommend turning on [SSM session logging](https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-create-iam-instance-profile.html#create-iam-instance-profile-ssn-logging) as well?

**Comment by jicowan** [comment]
Thanks for the suggestion @tomekchime. Do you have time to submit a PR for these changes?
