### ISSUE TITLE
Need to update to use Inspector v2

### ISSUE THREAD

**Issue by sotoiwa** [aws/aws-eks-best-practices#221]
**Describe the problem**
There is a recommendation to use Inspector for detection of host OS vulnerabilities. This recommendation is now for Inspector Classic and needs to be updated to use Inspector v2.

**References**
https://aws.github.io/aws-eks-best-practices/security/docs/hosts/#run-amazon-inspector-to-assess-hosts-for-exposure-vulnerabilities-and-deviations-from-best-practices

**Comment by jimmyraywv** [comment]
@sotoiwa Can you please submit a PR for these changes?

**Comment by sotoiwa** [comment]
PR #225 has been merged, closing issue.
