### ISSUE TITLE
Fargate pod incorrectly treated as "Task"

### ISSUE THREAD

**Issue by rafaelpereyra** [aws/aws-eks-best-practices#25]
**Describe the problem**
In the infrastructure page, a Fargate Pod is incorrectly referred as "Task". This common ocurrence lead to confusion with ECS service: 

**References**
Please include a link to the lines where the error appears.

> With EKS Fargate, AWS will automatically update the underlying infrastructure as updates become available. Oftentimes this can be done seamlessly, but there may be times when an update will cause your **task** to be rescheduled.

https://aws.github.io/aws-eks-best-practices/hosts/#treat-your-infrastructure-as-immutable-and-automate-the-replacement-of-your-worker-nodes

**Comment by jicowan** [comment]
Nice catch @rafaelpereyra.  I will fix it.
