### ISSUE TITLE
Karpenter: EC2 fleet allocation strategy used for Spot Instances

### ISSUE THREAD

**Issue by Pat-Ayres** [aws/aws-eks-best-practices#267]
The Karpenter section on [Instance Types that Karpenter can provision](https://aws.github.io/aws-eks-best-practices/karpenter/#avoid-overly-constraining-the-instance-types-that-karpenter-can-provision-especially-when-utilizing-spot) states:
> When using Spot, Karpenter uses the [Capacity Optimized](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-fleet-allocation-strategy.html)[Prioritized allocation strategy](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-fleet-allocation-strategy.html) to provision EC2 instances.

 However, the FAQ answer to [How does Karpenter dynamically select instance types?](https://karpenter.sh/v0.22.1/faq/#how-does-karpenter-dynamically-select-instance-types) states:
> If you are using the spot capacity type, Karpenter uses the price-capacity-optimized allocation strategy.

I checked the code and verified that it does appear to use [price-capacity-optimized allocation strategy](https://github.com/aws/karpenter/blob/2174c213f5c68c0436b5f2a3c515b1f0bce1afbe/pkg/cloudprovider/instance.go#L189).

**References**
[Direct link to doc line](https://github.com/aws/aws-eks-best-practices/blob/master/content/karpenter/index.md?plain=1#L234)

**Comment by jicowan** [comment]
@Pat-Ayres thanks for the issue. That is a recent change. I will see to it that it gets updated.

**Comment by jicowan** [comment]
Made requested changes.
