### ISSUE TITLE
HttpPutResponseHopLimit missing from section about increasing same

### ISSUE THREAD

**Issue by jbma2z** [aws/aws-eks-best-practices#270]
**Describe the problem**
In this section, the specific property name, `HttpPutResponseHopLimit`, is not mentioned for increasing the hop count.

Also, searching the guide for `HttpPutResponseHopLimit` returns no results.

**References**
https://aws.github.io/aws-eks-best-practices/security/docs/iam/#when-your-application-needs-access-to-imds-use-imdsv2-and-increase-the-hop-limit-on-ec2-instances-to-2
![image (3)](https://user-images.githubusercontent.com/94412479/213811120-ca5a0b3d-46c8-4b6e-989c-b8146150b331.png)

**Comment by jicowan** [comment]
Can you elaborate @jbma2z. Is setting the hop count to 1 insufficient as seen in this recommendation, https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node? How can we make this better?

**Comment by jbma2z** [comment]
Previously the Terraform block with the `metadata_options` did not return from searching the document (as is evident from the screen capture). 
The document as it is now is sufficient as it can be easily inferred what setting needs to be changed and the value is searchable.
