### ISSUE TITLE
Unclear explanation of in-transit nitro encryption support

### ISSUE THREAD

**Issue by halovanic** [aws/aws-eks-best-practices#280]
https://aws.github.io/aws-eks-best-practices/security/docs/network/#nitro-instances

This section reads "Traffic exchanged between the following Nitro instance types C5n, G4, I3en, M5dn, M5n, P3dn, R5dn, and R5n, is automatically encrypted by default" which reads as an exhaustive list of instance types.

This document indicates that many other types support this encryption, many of which are supported in EKS:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/data-protection.html#encryption-transit

I noticed that earlier versions of this document used "e.g." to indicate these were only examples of instance types.  Without this it reads like the use of EKS may limit which types can use this encryption.

**Comment by jicowan** [comment]
Thanks @halovanic. I think this might be a regression. I'll change it to e.g. because a) the list of instances will change as we release new instance types and b) the list is only a small subset of the complete list of instances that support TLS.
