### ISSUE TITLE
Add details of mixing Spot and OnDemand in CAS

### ISSUE THREAD

**Issue by shahadc** [aws/aws-eks-best-practices#310]
https://aws.github.io/aws-eks-best-practices/cluster-autoscaling/#spot-instances

The spot section currently recommends using AutoScaling Groups (ASGs) with 100% OnDemand or 100% spot (to prevent rebalancing activities when CAS scales the ASG).  Could this section have 2 things added to it?

1) Add the ASG activity history message that will be displayed when rebalancing happens, so users can find this page when searching for it.  There will be 2 activity history messages one right after the other, with the formats
>At 2023-04-10T21:05:28Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 1 to 2
>At 2023-04-10T21:06:28Z an instance was taken out of service in response to a difference between desired and actual capacity, shrinking the capacity from 2 to 1

2) If there's any way to tell CAS to balance a set percentage of nodes for the Spot vs OnDemand NodeGroups, include the settings for that in the doc.

**Comment by jicowan** [comment]
@shahadc thanks for the suggestion. A couple of questions. First, why is it important to know when rebalancing occurs? Second, there is no way to to tell CAS to rebalance a percentage of nodes. Spot capacity determines when instances are replaced. If you're referring to AZBalancing, that too, is an ASG feature. You can enable/disable it, but you can't configure a percentage of instances to replace. Generally speaking, if you use mixed instance types with Spot node groups, you should have fewer interruptions.

**Comment by shahadc** [comment]
Hi @jicowan 
Answers to your questions below:

1) "Why is it important to know" - for troubleshooting unexpected terminations caused by the ASG rebalancing the spot/OnDemand mix.  I've seen many people get confused by the wording in these messages when using CAS, and currently there's nothing in the documentation to tell them why the extra activities are happening, or how to fix it

2) I'm not talking about either rebalancing activity here, I'm talking about setting weights for ideally how the cluster should be split between spot and OnDemand (or more generically, what split of the cluster should be fulfilled by each Node Group).  Essentially, I'm looking for a way to mimic the ASG setting for "Launch X% of the group as Spot and Y% as OnDemand" in CAS by setting what % of capacity should be fulfilled by each Node Group; since its recommended for a given ASG to be 100% spot or 100% OnDemand when using CAS.

**Comment by jicowan** [comment]
@shahadc you can use the priority expander with CAS. It allows you to assign "weights" to different node groups. 

I believe there are better ways to determine when rebalancing occurs than logs, e.g. an ASG lifecycle hooks, instance metadata, or a CloudWatch Event.

**Comment by shahadc** [comment]
@jicowan 
Thanks for confirming.  I'm more familiar with ASG than EKS/CAS, so it might just be my lack of familiarity, but I think adding the info on expanders after the recommendation to have each ASG be 100% Spot or OnDemand in this doc would be helpful.

For Market Option rebalancing, there isn't any way other than the ASG activity history to know when it happens.  ASG does not currently emit any specific events for it, and there's no specific indication in the launch or terminate events that the cause is Market Option rebalancing

**Comment by jicowan** [comment]
I think we already have some guidance on using the priority expander. See https://aws.github.io/aws-eks-best-practices/cluster-autoscaling/#prioritizing-a-node-group-asg. I'll have to look at what messages/events are triggered during a rebalancing event. Perhaps we can provide more guidance around that.
