### ISSUE TITLE
Including Kyverno approach for PSP migration 

### ISSUE THREAD

**Issue by shapirov103** [aws/aws-eks-best-practices#331]
**Is your idea request related to a problem that you've solved? Please describe.**
Add Kyverno-based PSP migration strategy. It maybe a paragraph with a reference to this [post](https://main.kyverno.io/blog/2023/05/24/podsecuritypolicy-migration-with-kyverno/)

**Describe the best practice**
Following the removal (after deprecation) of PSPs from latest versions of Kubernetes, customers who are less agile to adopt new versions of Kubernetes (EKS) are now looking for a migration path. Kyverno is an OSS and Kubernetes native policy engine that customers can take advantage of. In addition, Nirmata (the primary sponsor of Kyverno OSS) is an AWS partner and can provide both community and enterprise assistance to the customers migrating away from PSPs.

**Describe alternatives you've considered**
OPA/Gatekeeper route for the same.

**Additional context**
Please let me know if this is something that the owners of this repository ready to review/accept and we will submit a PR. This issue was created to start a discussion and decide on the format of the contribution in case there is interest. Please add comments to this issue with your thoughts.

**Comment by jicowan** [comment]
Hi @shapirov103, we already have content on migrating from PSPs to PSS/PSA which mentions Kyverno as an alternative to PSPs. We also published a blog last year on how you can use Kyverno to grant exceptions to PSS policies, https://aws.amazon.com/blogs/containers/managing-pod-security-on-amazon-eks-with-kyverno/ which I would not be averse to adding to the tools and resources section at the bottom of the page. The blog you reference appears to convert PSPs into Kyverno policies which is fine. I would be okay with adding a brief paragraph about this solution outlined in the blog follow by a link to the blog itself. @jimmyraywv for his thoughts.

**Comment by chipzoller** [comment]
Please see PR #333 for a proposed update to the relevant section of the docs which incorporates links to both Kyverno project blog as well as prior AWS blog.
