### ISSUE TITLE
EKS currently has native support for OIDC Authentication

### ISSUE THREAD

**Issue by Missshao** [aws/aws-eks-best-practices#34]
**Describe the problem**
https://github.com/aws/aws-eks-best-practices/blob/master/content/security/docs/iam.md
“EKS currently has native support for webhook token authentication and service account tokens.”

I think EKS now support OIDC .

**References**
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

**Comment by mhausenblas** [comment]
Nope, IRSA *uses* the AWS OIDC provider. What you mean is https://github.com/aws/containers-roadmap/issues/166
