### ISSUE TITLE
kube-apiserver metric got renamed from etcd_db_total_size_in_bytes to apiserver_storage_db_total_size_in_bytes starting with EKS 1.26

### ISSUE THREAD

**Issue by youwalther65** [aws/aws-eks-best-practices#345]
**Describe the problem**
In section [Know limits and service quotas](https://aws.github.io/aws-eks-best-practices/reliability/docs/controlplane/#know-limits-and-service-quotas) in chapter [Control plane](https://aws.github.io/aws-eks-best-practices/reliability/docs/controlplane/) we recommend monitoring the gauge etcd_db_total_size_in_bytes. Starting with K8s/EKS v1.26 this attribute is renamed to apiserver_storage_db_total_size_in_bytes. For reference see apiserver [metrics.go 1.26](https://github.com/kubernetes/apiserver/blob/release-1.26/pkg/storage/etcd3/metrics/metrics.go#L58-L66)

**References**
Mentioned in [Know limits and service quotas](https://aws.github.io/aws-eks-best-practices/reliability/docs/controlplane/#know-limits-and-service-quotas)

**Comment by jicowan** [comment]
Thanks @youwalther65. Can you submit a PR for this change?

**Comment by youwalther65** [comment]
@jicowan Please see my proposal in [PR](https://github.com/youwalther65/aws-eks-best-practices/pull/1)
