### ISSUE TITLE
Pod Security Admission Incorrectly Noted as Still in Beta

### ISSUE THREAD

**Issue by GarrettPoore** [aws/aws-eks-best-practices#346]
**Describe the problem**
At the bottom of the Pod Security Admission section, there is an attention block saying that PSA is not GA yet. As of 1.25, [PSA is GA](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/).

**References**
[Pod Security Standards (PSS) and Pod Security Admission (PSA) section](https://aws.github.io/aws-eks-best-practices/security/docs/pods/#pod-security-standards-pss-and-pod-security-admission-psa)

**Comment by jicowan** [comment]
Thanks @GarrettPoore. I'll make the change.
