### ISSUE TITLE
Documentation broken link

### ISSUE THREAD

**Issue by lucasrf1984** [aws/aws-eks-best-practices#386]
**Describe the problem**

There is a broken link in the documentation reference on this page:

https://aws.github.io/aws-eks-best-practices/networking/monitoring/#monitoring-coredns-traffic-for-dns-throttling-issues

The broken link can be found on above URL right on the link to: See [Monitor CoreDNS Metrics](https://aws.github.io/aws-eks-best-practices/reliability/docs/networkmanagement/#monitor-coredns-metrics) for further information.

**References**
Broken link: https://aws.github.io/aws-eks-best-practices/reliability/docs/networkmanagement/#monitor-coredns-metrics

**Comment by jicowan** [comment]
Fixed
