### ISSUE TITLE
Cross reference to a new AMI (example) for creating EKS AMI for RHEL nodes

### ISSUE THREAD

**Issue by jaykayv-aws** [aws/aws-eks-best-practices#418]
I want to cross reference https://github.com/aws-samples/amazon-eks-ami-rhel as a example for building EKS AMI for RHEL nodes. I am working with a customer  who has asked us whether this link can be made visible and easily accessible for end customers. They were hitherto not aware of this Github repo and were spending a lot of time building their own customer RHEL based EKS optimised AMIs

**Comment by jicowan** [comment]
Please submit a PR for this change @jaykayv-aws

**Comment by jaykayv-aws** [comment]
Thanks for the nudge @jicowan . Will send a PR soon
