### ISSUE TITLE
Broken links in documentation for scaling apps based on custom or external metrics

### ISSUE THREAD

**Issue by mohalone911** [aws/aws-eks-best-practices#426]
**Describe the problem**
A clear and concise description of what is wrong with the documentation.  

Multiple links in the section https://aws.github.io/aws-eks-best-practices/reliability/docs/application/#scaling-applications-based-on-custom-or-external-metrics are broken and goto "404 - page not found" error.

**References**
Please include a link to the lines where the error appears.
[Custom Metrics]
(https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/custom-metrics-api.md)", 

[Kubernetes Documentation]
(https://github.com/kubernetes/metrics/blob/master/IMPLEMENTATIONS.md#custom-metrics-api).

[External metrics]
(https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/external-metrics-api.md)

**Comment by jicowan** [comment]
fixed.
