### ISSUE TITLE
Spelling error in Control Plane section

### ISSUE THREAD

**Issue by jbma2z** [aws/aws-eks-best-practices#489]
**Describe the problem**
That is not how you spell `retrieving`. Both the anchor and text need to be updated.

**References**
Please include a link to the lines where the error appears.
https://aws.github.io/aws-eks-best-practices/scalability/docs/control-plane/#retreiving-resources-in-the-api-server
```
<h2 id="retreiving-resources-in-the-api-server">Retreiving resources in the API server<a class="headerlink" href="#retreiving-resources-in-the-api-server" title="Permanent link">¶</a></h2>
```

**Comment by jbma2z** [comment]
Created PR for control-plane.md:
https://github.com/aws/aws-eks-best-practices/pull/490

**Comment by za** [comment]
PR merged. We can close this issue. cc: @svennam92
