### ISSUE TITLE
The maximum pod count for all nodes in a particular node group is defined by the lowest maximum pod count of any single instance type in the node group.

### ISSUE THREAD

**Issue by afreakk** [aws/aws-eks-best-practices#506]
**Describe the problem**
Like it says here https://github.com/aws/aws-eks-best-practices/blob/c3d679ae932d82327ea6f4b40d5a4f277254ddb8/content/networking/prefix-mode/index_linux.md?plain=1#L51
I dont really understand, I've set 
```
/etc/eks/bootstrap.sh %s --use-max-pods false --kubelet-extra-args '--max-pods=110'
```
In 4/5 nodes, but in 1/5 nodes i tried setting
```
/etc/eks/bootstrap.sh %s --use-max-pods false --kubelet-extra-args '--max-pods=6'
```
But it does not seem to affect the other nodes, they still have 110 allocatable pods when i run `kubectl describe nodes`.
and are running with many more than 6 pods currently.

I might be missunderstanding that advice, or its wrong?

The  reason im testing is, I want to have it like this:
With a very diverse nodegroup with many instancetypes
```
MAX_PODS=$(/etc/eks/max-pods-calculator.sh --instance-type-from-imds --cni-version 1.10.0  --cni-prefix-delegation-enabled)
/etc/eks/bootstrap.sh %s --use-max-pods false --kubelet-extra-args "--max-pods=$MAX_PODS"
```
But if  everyone gets max-pods of the lowest node, that seems  like  a bad idea

**References**
https://github.com/aws/aws-eks-best-practices/blob/c3d679ae932d82327ea6f4b40d5a4f277254ddb8/content/networking/prefix-mode/index_linux.md?plain=1#L51

**Comment by ROunofF** [comment]
This section is about "Use Similar Instance Types in the same Node Group". 

So this warning is for the managed node group. EKS will check all the instance and configure the "lowest" maximum among all instances. If you override it per node, there is a chance you aren't using the MNG.

So if you have :
- t3.large 35
- t3.xlarge 58
- t3.2xlarge 58


You would end up with 35 configure on all nodes.
