### ISSUE TITLE
Monitoring Control Plane Metrics shows guidance for deprecated metrics

### ISSUE THREAD

**Issue by cbb330** [aws/aws-eks-best-practices#64]
**Describe the problem**
Metric |  Notes
-- | -- 
etcd_request_latencies_summary |  Deprecated: https://github.com/kubernetes/kubernetes/pull/76496 -  Replaced with etcd_request_duration_seconds
etcd_helper_cache_entry_total |   Deprecated: https://github.com/kubernetes/kubernetes/pull/79520
etcd_helper_cache_hit_total |   Deprecated: https://github.com/kubernetes/kubernetes/pull/79520
etcd_helper_cache_miss_total |   Deprecated: https://github.com/kubernetes/kubernetes/pull/79520
etcd_request_cache_get_duration_seconds |   Deprecated: https://github.com/kubernetes/kubernetes/pull/79520  
etcd_request_cache_add_duration_seconds |   Deprecated: https://github.com/kubernetes/kubernetes/pull/79520

The PR/code changes for this deprecation do not list alternatives.

Can anyone provide alternatives for these deprecated metrics? 

**References**
https://aws.github.io/aws-eks-best-practices/reliability/docs/controlplane/#monitor-control-plane-metrics

**Comment by realvz** [comment]
Looks like most of etcd metrics mentioned here have been deprecated without providing a replacement metric. I will remove them for now until we can find alternatives.

**Comment by jicowan** [comment]
@realvz can we close this?

**Comment by realvz** [comment]
Closing the issue since these metrics are no longer available.
