### ISSUE TITLE
Windows Caveats

### ISSUE THREAD

**Issue by andrewpurdin** [aws/aws-eks-best-practices#68]
Speaking as someone who is attempting to run a mixed EKS cluster with both Windows and Linux workloads, there are several caveats and best practices that are specific to running Windows nodes that it would be helpful to highlight. It would also be beneficial to point out if certain tools or recommendations are incompatible with Windows. 

Perhaps the best solution to this overall is an entire section dedicated to Windows EKS best practices, but intermingling notes about running Windows with existing sections could work as well. 

I hope this feedback is helpful, even though it didn't quite fit the defined template.

**Comment by jicowan** [comment]
@andrewpurdin As you suggested, we probably need a section dedicated to running Windows containers. I'll see whether I can get someone to do that.

**Comment by jicowan** [comment]
Will be publishing guidance for running Windows worker nodes and Windows containers shortly.
