### ISSUE TITLE
Navigation of "Data Encryption and Secrets Management" page is broken 

### ISSUE THREAD

**Issue by sotoiwa** [aws/aws-eks-best-practices#94]
**Describe the problem**
The navigation in the right pane of the "Data Encryption and Secrets Management" page is broken.
I think it can be fixed by putting "Data Encryption and Secrets Management" as the title (H1) and making "Encryption at rest" and "Secrets management" one step down to H2.

**References**
https://aws.github.io/aws-eks-best-practices/security/docs/data/

**Comment by jicowan** [comment]
Thanks @sotoiwa. Those links are automatically generated by mkdocs. I will try rebuilding the pages.  Incidentally, the links work on my browser. I wonder if it's a caching issue.
