### ISSUE TITLE
Actuary has not been updated for 4 years

### ISSUE THREAD

**Issue by sotoiwa** [aws/aws-eks-best-practices#96]
**Describe the problem**
"actuary" listed in the tools section of the compliance page hasn't been updated for 4 years. I don't think it's a good idea to put a link to a tool that is not active. How about removing it?

**References**
https://aws.github.io/aws-eks-best-practices/security/docs/compliance/#tools-and-resources

**Comment by jicowan** [comment]
Removed link.
