### ISSUE TITLE
Propose to put Dockle on the list of tools for image security.

### ISSUE THREAD

**Issue by sotoiwa** [aws/aws-eks-best-practices#97]
**Describe the best practice**
[Dockle](https://github.com/goodwithtech/dockle) is a good tool as a linter for Docker images. It has got 1.5k stars and is actively maintained. I would like to propose to put it on the list of tools for image security.

https://aws.github.io/aws-eks-best-practices/security/docs/image/#tools.

**Comment by sotoiwa** [comment]
Yes. I think it's relatively popular in Japan. Based on the number of stars, I think it is also used worldwide. I have introduced it to my customers and have them use it in their build pipelines.

**Comment by jicowan** [comment]
Done.
