### ISSUE TITLE
Better to introduce hadolint than dockerfile-lint

### ISSUE THREAD

**Issue by sotoiwa** [aws/aws-eks-best-practices#98]
**Describe the problem**
In the "Lint your Dockerfiles" section, [dockerfile-lint](https://github.com/projectatomic/dockerfile_lint) is introduced, but [hadolint](https://github.com/hadolint/hadolint) has much more stars on GitHub. Why not introduce hadolint here? dockerfile-lint has fewer stars and doesn't seem to be actively maintained.

**References**
https://aws.github.io/aws-eks-best-practices/security/docs/image/#lint-your-dockerfiles

**Comment by jicowan** [comment]
@sotoiwa Hadolint is already in the tools section. Do you think it deserves to be prominently featured in the section on linting your Dockerfiles?

**Comment by sotoiwa** [comment]
Yes, I think so. [Dockerfile-lint](https://github.com/projectatomic/dockerfile_lint) has only 37 stars and the last commit was 10 months ago. [Hadolint](https://github.com/hadolint/hadolint) has 5.3k stars and had another commit yesterday.
