### ISSUE TITLE
apt require `apt update` before `apt upgrade`

### ISSUE THREAD

**Issue by armaniacs** [aws/aws-eks-best-practices#99]
Hi,
Thanks for writing 
```You should include RUN apt-get upgrade in your Dockerfiles to upgrade the packages in your images.```
Could you rewrite two things

1. Please use `apt-get update && apt-get upgrade`. `update` is required before `upgrade`. It is a one of frequently showing mistake...
2. `apt clean` is also useful. It can clean files in /var/cache/apt/archives.

**References**
https://aws.github.io/aws-eks-best-practices/security/docs/image/#update-the-packages-in-your-container-images

https://www.debian.org/doc/manuals/debian-handbook/sect.apt-get.en.html

**Comment by armaniacs** [comment]
For alpine image build, `RUN apk update && apk add --no-cache git` is described. Please follow for apt based distributions. Thanks.

**Comment by jicowan** [comment]
done.
